### ISSUE TITLE
More of information rather than issue

### ISSUE THREAD

**Issue by vysr2939** [agnoster/duplicator#11]
Hi Agnoster,
Thanks for the work, i am curious to know if it fits my scenerio.
I already have service running listening to tcp on particular port, can i use this to bind to the same port and duplicate the traffic to the other. Since the duplicator function takes 3 arguments to listen, duplicate  and forward, it's confusing for me because i don't want to forward anywhere, some other service is taking care of that. 
I'm new to nodejs and stuffs, so any suggestions would be helpful.

Thanks
Vishal

**Comment by agnoster** [comment]
You can't bind to the same port another service is listening on - it's one service per port (per host/networking interface) - unless you do something super crazy I guess.

The way duplicator works is that you bind to the port you want the outside world to connect to, you forward to the "real" backend service, and then duplicate to... wherever you want.

So if you have an existing service on some host running on port 80, and you want to see how a new beta server will handle the load, you would either switch the existing service to run on another port (let's say 8081) and have duplicator bind to port 80 and forward to 8081, or you could put a proxy in between and change the DNS so that customers connect to the duplicator (which forwards/proxies traffic to the "real" service).
